#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ticketvendor")]
public partial class TicketVendorDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertmt_user(mt_user instance);
  partial void Updatemt_user(mt_user instance);
  partial void Deletemt_user(mt_user instance);
  #endregion
	
	public TicketVendorDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ticketvendorConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TicketVendorDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TicketVendorDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TicketVendorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TicketVendorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<mt_user> mt_users
	{
		get
		{
			return this.GetTable<mt_user>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mt_user")]
public partial class mt_user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _uid;
	
	private string _nav_uid;
	
	private string _uname;
	
	private string _pwd;
	
	private string _utype;
	
	private string _agent_code;
	
	private string _pos;
	
	private string _dl_user;
	
	private string _abacus_ipcc;
	
	private string _abacus_printer;
	
	private string _amadeus_ipcc;
	
	private string _amadeus_printer;
	
	private string _galileo_ipcc;
	
	private string _galileo_printer;
	
	private string _send2email;
	
	private string _gmcard_no;
	
	private System.Nullable<System.DateTime> _create_date;
	
	private string _create_by;
	
	private System.Nullable<System.DateTime> _update_date;
	
	private string _update_by;
	
	private System.Nullable<char> _user_status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(string value);
    partial void OnuidChanged();
    partial void Onnav_uidChanging(string value);
    partial void Onnav_uidChanged();
    partial void OnunameChanging(string value);
    partial void OnunameChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnutypeChanging(string value);
    partial void OnutypeChanged();
    partial void Onagent_codeChanging(string value);
    partial void Onagent_codeChanged();
    partial void OnposChanging(string value);
    partial void OnposChanged();
    partial void Ondl_userChanging(string value);
    partial void Ondl_userChanged();
    partial void Onabacus_ipccChanging(string value);
    partial void Onabacus_ipccChanged();
    partial void Onabacus_printerChanging(string value);
    partial void Onabacus_printerChanged();
    partial void Onamadeus_ipccChanging(string value);
    partial void Onamadeus_ipccChanged();
    partial void Onamadeus_printerChanging(string value);
    partial void Onamadeus_printerChanged();
    partial void Ongalileo_ipccChanging(string value);
    partial void Ongalileo_ipccChanged();
    partial void Ongalileo_printerChanging(string value);
    partial void Ongalileo_printerChanged();
    partial void Onsend2emailChanging(string value);
    partial void Onsend2emailChanged();
    partial void Ongmcard_noChanging(string value);
    partial void Ongmcard_noChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void Oncreate_byChanging(string value);
    partial void Oncreate_byChanged();
    partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dateChanged();
    partial void Onupdate_byChanging(string value);
    partial void Onupdate_byChanged();
    partial void Onuser_statusChanging(System.Nullable<char> value);
    partial void Onuser_statusChanged();
    #endregion
	
	public mt_user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string uid
	{
		get
		{
			return this._uid;
		}
		set
		{
			if ((this._uid != value))
			{
				this.OnuidChanging(value);
				this.SendPropertyChanging();
				this._uid = value;
				this.SendPropertyChanged("uid");
				this.OnuidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nav_uid", DbType="NVarChar(50)")]
	public string nav_uid
	{
		get
		{
			return this._nav_uid;
		}
		set
		{
			if ((this._nav_uid != value))
			{
				this.Onnav_uidChanging(value);
				this.SendPropertyChanging();
				this._nav_uid = value;
				this.SendPropertyChanged("nav_uid");
				this.Onnav_uidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="NVarChar(50)")]
	public string uname
	{
		get
		{
			return this._uname;
		}
		set
		{
			if ((this._uname != value))
			{
				this.OnunameChanging(value);
				this.SendPropertyChanging();
				this._uname = value;
				this.SendPropertyChanged("uname");
				this.OnunameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(15)")]
	public string pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this.OnpwdChanging(value);
				this.SendPropertyChanging();
				this._pwd = value;
				this.SendPropertyChanged("pwd");
				this.OnpwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_utype", DbType="NChar(3)")]
	public string utype
	{
		get
		{
			return this._utype;
		}
		set
		{
			if ((this._utype != value))
			{
				this.OnutypeChanging(value);
				this.SendPropertyChanging();
				this._utype = value;
				this.SendPropertyChanged("utype");
				this.OnutypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agent_code", DbType="NChar(6)")]
	public string agent_code
	{
		get
		{
			return this._agent_code;
		}
		set
		{
			if ((this._agent_code != value))
			{
				this.Onagent_codeChanging(value);
				this.SendPropertyChanging();
				this._agent_code = value;
				this.SendPropertyChanged("agent_code");
				this.Onagent_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos", DbType="NChar(3)")]
	public string pos
	{
		get
		{
			return this._pos;
		}
		set
		{
			if ((this._pos != value))
			{
				this.OnposChanging(value);
				this.SendPropertyChanging();
				this._pos = value;
				this.SendPropertyChanged("pos");
				this.OnposChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_user", DbType="NChar(2)")]
	public string dl_user
	{
		get
		{
			return this._dl_user;
		}
		set
		{
			if ((this._dl_user != value))
			{
				this.Ondl_userChanging(value);
				this.SendPropertyChanging();
				this._dl_user = value;
				this.SendPropertyChanged("dl_user");
				this.Ondl_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abacus_ipcc", DbType="NChar(4)")]
	public string abacus_ipcc
	{
		get
		{
			return this._abacus_ipcc;
		}
		set
		{
			if ((this._abacus_ipcc != value))
			{
				this.Onabacus_ipccChanging(value);
				this.SendPropertyChanging();
				this._abacus_ipcc = value;
				this.SendPropertyChanged("abacus_ipcc");
				this.Onabacus_ipccChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abacus_printer", DbType="NVarChar(10)")]
	public string abacus_printer
	{
		get
		{
			return this._abacus_printer;
		}
		set
		{
			if ((this._abacus_printer != value))
			{
				this.Onabacus_printerChanging(value);
				this.SendPropertyChanging();
				this._abacus_printer = value;
				this.SendPropertyChanged("abacus_printer");
				this.Onabacus_printerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amadeus_ipcc", DbType="NChar(4)")]
	public string amadeus_ipcc
	{
		get
		{
			return this._amadeus_ipcc;
		}
		set
		{
			if ((this._amadeus_ipcc != value))
			{
				this.Onamadeus_ipccChanging(value);
				this.SendPropertyChanging();
				this._amadeus_ipcc = value;
				this.SendPropertyChanged("amadeus_ipcc");
				this.Onamadeus_ipccChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amadeus_printer", DbType="NVarChar(10)")]
	public string amadeus_printer
	{
		get
		{
			return this._amadeus_printer;
		}
		set
		{
			if ((this._amadeus_printer != value))
			{
				this.Onamadeus_printerChanging(value);
				this.SendPropertyChanging();
				this._amadeus_printer = value;
				this.SendPropertyChanged("amadeus_printer");
				this.Onamadeus_printerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galileo_ipcc", DbType="NChar(4)")]
	public string galileo_ipcc
	{
		get
		{
			return this._galileo_ipcc;
		}
		set
		{
			if ((this._galileo_ipcc != value))
			{
				this.Ongalileo_ipccChanging(value);
				this.SendPropertyChanging();
				this._galileo_ipcc = value;
				this.SendPropertyChanged("galileo_ipcc");
				this.Ongalileo_ipccChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_galileo_printer", DbType="NVarChar(10)")]
	public string galileo_printer
	{
		get
		{
			return this._galileo_printer;
		}
		set
		{
			if ((this._galileo_printer != value))
			{
				this.Ongalileo_printerChanging(value);
				this.SendPropertyChanging();
				this._galileo_printer = value;
				this.SendPropertyChanged("galileo_printer");
				this.Ongalileo_printerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_send2email", DbType="NVarChar(255)")]
	public string send2email
	{
		get
		{
			return this._send2email;
		}
		set
		{
			if ((this._send2email != value))
			{
				this.Onsend2emailChanging(value);
				this.SendPropertyChanging();
				this._send2email = value;
				this.SendPropertyChanged("send2email");
				this.Onsend2emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmcard_no", DbType="NVarChar(20)")]
	public string gmcard_no
	{
		get
		{
			return this._gmcard_no;
		}
		set
		{
			if ((this._gmcard_no != value))
			{
				this.Ongmcard_noChanging(value);
				this.SendPropertyChanging();
				this._gmcard_no = value;
				this.SendPropertyChanged("gmcard_no");
				this.Ongmcard_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> create_date
	{
		get
		{
			return this._create_date;
		}
		set
		{
			if ((this._create_date != value))
			{
				this.Oncreate_dateChanging(value);
				this.SendPropertyChanging();
				this._create_date = value;
				this.SendPropertyChanged("create_date");
				this.Oncreate_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_by", DbType="NVarChar(15)")]
	public string create_by
	{
		get
		{
			return this._create_by;
		}
		set
		{
			if ((this._create_by != value))
			{
				this.Oncreate_byChanging(value);
				this.SendPropertyChanging();
				this._create_by = value;
				this.SendPropertyChanged("create_by");
				this.Oncreate_byChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> update_date
	{
		get
		{
			return this._update_date;
		}
		set
		{
			if ((this._update_date != value))
			{
				this.Onupdate_dateChanging(value);
				this.SendPropertyChanging();
				this._update_date = value;
				this.SendPropertyChanged("update_date");
				this.Onupdate_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_by", DbType="NVarChar(15)")]
	public string update_by
	{
		get
		{
			return this._update_by;
		}
		set
		{
			if ((this._update_by != value))
			{
				this.Onupdate_byChanging(value);
				this.SendPropertyChanging();
				this._update_by = value;
				this.SendPropertyChanged("update_by");
				this.Onupdate_byChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_status", DbType="NChar(1)")]
	public System.Nullable<char> user_status
	{
		get
		{
			return this._user_status;
		}
		set
		{
			if ((this._user_status != value))
			{
				this.Onuser_statusChanging(value);
				this.SendPropertyChanging();
				this._user_status = value;
				this.SendPropertyChanged("user_status");
				this.Onuser_statusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
