#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webfares2011")]
public partial class WebfaresDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttr_login_log(tr_login_log instance);
  partial void Updatetr_login_log(tr_login_log instance);
  partial void Deletetr_login_log(tr_login_log instance);
  #endregion
	
	public WebfaresDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["webfares2011ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public WebfaresDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WebfaresDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WebfaresDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WebfaresDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tr_login_log> tr_login_logs
	{
		get
		{
			return this.GetTable<tr_login_log>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tr_login_log")]
public partial class tr_login_log : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _uid;
	
	private string _ip_address;
	
	private System.Nullable<System.DateTime> _login_time;
	
	private System.Nullable<System.DateTime> _logout_time;
	
	private string _browser;
	
	private string _logout_by;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuidChanging(string value);
    partial void OnuidChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void Onlogin_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onlogin_timeChanged();
    partial void Onlogout_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onlogout_timeChanged();
    partial void OnbrowserChanging(string value);
    partial void OnbrowserChanged();
    partial void Onlogout_byChanging(string value);
    partial void Onlogout_byChanged();
    #endregion
	
	public tr_login_log()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(20)")]
	public string uid
	{
		get
		{
			return this._uid;
		}
		set
		{
			if ((this._uid != value))
			{
				this.OnuidChanging(value);
				this.SendPropertyChanging();
				this._uid = value;
				this.SendPropertyChanged("uid");
				this.OnuidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="NVarChar(20)")]
	public string ip_address
	{
		get
		{
			return this._ip_address;
		}
		set
		{
			if ((this._ip_address != value))
			{
				this.Onip_addressChanging(value);
				this.SendPropertyChanging();
				this._ip_address = value;
				this.SendPropertyChanged("ip_address");
				this.Onip_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_time", DbType="DateTime")]
	public System.Nullable<System.DateTime> login_time
	{
		get
		{
			return this._login_time;
		}
		set
		{
			if ((this._login_time != value))
			{
				this.Onlogin_timeChanging(value);
				this.SendPropertyChanging();
				this._login_time = value;
				this.SendPropertyChanged("login_time");
				this.Onlogin_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logout_time", DbType="DateTime")]
	public System.Nullable<System.DateTime> logout_time
	{
		get
		{
			return this._logout_time;
		}
		set
		{
			if ((this._logout_time != value))
			{
				this.Onlogout_timeChanging(value);
				this.SendPropertyChanging();
				this._logout_time = value;
				this.SendPropertyChanged("logout_time");
				this.Onlogout_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_browser", DbType="NVarChar(255)")]
	public string browser
	{
		get
		{
			return this._browser;
		}
		set
		{
			if ((this._browser != value))
			{
				this.OnbrowserChanging(value);
				this.SendPropertyChanging();
				this._browser = value;
				this.SendPropertyChanged("browser");
				this.OnbrowserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logout_by", DbType="NVarChar(10)")]
	public string logout_by
	{
		get
		{
			return this._logout_by;
		}
		set
		{
			if ((this._logout_by != value))
			{
				this.Onlogout_byChanging(value);
				this.SendPropertyChanging();
				this._logout_by = value;
				this.SendPropertyChanged("logout_by");
				this.Onlogout_byChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
